# Generated by Django 4.2.16 on 2026-05-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0049_drug_exposure_end_date_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
