# Generated by Django 4.2.16 on 2026-05-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0064_add_organization_fk_to_provenance_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relationship_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('relationship_name', models.CharField(max_length=255)),
                ('is_hierarchical', models.CharField(max_length=1)),
                ('defines_ancestry', models.CharField(max_length=1)),
                ('reverse_relationship_id', models.CharField(max_length=20)),
                ('relationship_concept_id', models.IntegerField()),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.CreateModel(
            name='ConceptRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
                ('concept_1', models.ForeignKey(db_column='concept_id_1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relationships_as_source', to='omop_core.concept')),
                ('concept_2', models.ForeignKey(db_column='concept_id_2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='relationships_as_target', to='omop_core.concept')),
                ('relationship', models.ForeignKey(db_column='relationship_id', on_delete=django.db.models.deletion.DO_NOTHING, to='omop_core.relationship')),
            ],
            options={
                'db_table': 'concept_relationship',
                'unique_together': {('concept_1', 'concept_2', 'relationship')},
            },
        ),
        migrations.CreateModel(
            name='ConceptAncestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_levels_of_separation', models.IntegerField()),
                ('max_levels_of_separation', models.IntegerField()),
                ('ancestor_concept', models.ForeignKey(db_column='ancestor_concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='descendants', to='omop_core.concept')),
                ('descendant_concept', models.ForeignKey(db_column='descendant_concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ancestors', to='omop_core.concept')),
            ],
            options={
                'db_table': 'concept_ancestor',
                'unique_together': {('ancestor_concept', 'descendant_concept')},
            },
        ),
    ]
