# Generated by Django 4.2.16 on 2026-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0065_add_vocabulary_relationship_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='defines_ancestry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='is_hierarchical',
            field=models.IntegerField(),
        ),
    ]
