# Generated by Django 4.2.16 on 2026-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0075_add_person_id_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loincclass',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
