# Generated by Django 4.2.16 on 2026-05-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omop_oncology', '0004_ai_line_of_therapy_summary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ailineoftherapysummary',
            new_name='ai_line_of__episode_b79358_idx',
            old_name='ai_lot_episode_idx',
        ),
        migrations.RenameIndex(
            model_name='ailineoftherapysummary',
            new_name='ai_line_of__ai_line_10ecde_idx',
            old_name='ai_lot_source_id_idx',
        ),
    ]
