# Generated by Django 4.2.16 on 2026-05-22 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_remove_patientmessage_read_at_patientmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'identities',
                'db_table': 'identity',
            },
        ),
        migrations.AddConstraint(
            model_name='identity',
            constraint=models.UniqueConstraint(fields=('issuer', 'sub'), name='uq_identity_issuer_sub'),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='identity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_user', to='patient_portal.identity'),
        ),
    ]
